.gitignore
src/index.ts
src/modules/Checkbox/Checkbox.story.mdx
src/modules/Checkbox/Checkbox.story.tsx
src/modules/Checkbox/Checkbox.tsx
src/modules/Checkbox/index.ts
src/modules/TextInput/TextInput.story.mdx

Checkbox component mostly done for the first iteration.
Things to notice and to discuss:
Would like to keep usage of something like this on other components: 
``` typescript
const iconContainerStyle = cx(
styles.iconContainer,
showAsChecked && styles.iconContainerShowAsChecked,
checkedState && styles.iconContainerChecked,
disabled && styles.iconContainerDisabled
);
<div className={iconContainerStyle}>
</div>
```
which can be extendable to this:
``` typescript
const iconStyle = cx(
...["y-checkbox-icon", styles.icon],
...(showAsChecked ? ["icon-show-as-checked", styles.iconShowAsChecked] : []),
...(checkedState ? ["icon-checked", styles.iconChecked] : []),
...(disabled ? ["icon-disabled", styles.iconDisabled] : [])
);
<div className={iconStyle}>
</div>
```
These way we can set default …

Checkbox Component

---

src/modules/Divider/Divider.story.mdx
src/modules/Divider/Divider.tsx
src/modules/Divider/index.ts

In this PR we add the Divider module.
Please check out the storybook for a complete description of the defined API and extendable styles.

Add Divider module

---

src/modules/Tab/Tab.story.mdx
src/modules/Tab/Tab.tsx
src/modules/Tab/TabGroup.story.tsx
src/modules/Tab/TabGroup.tsx
src/modules/Tab/index.ts
src/modules/index.ts

In this PR, we add the `Tab` module to the diana design system, which includes the`Tab` and `TabGroup` components.
For detailed info please check the storybook.

Add Tab module

---

modules/modal/index.ts
modules/modal/package.json
modules/textInput/package.json
scaffold/package.json.scaffold

Some packages were wrongly pointing to an inexistent file upon build. This PR aims to fixed them!

Fixed some falty package.json

---

modules/assets/index.ts
package.json
scripts/aux/iconScriptTemplates.ts
scripts/custom.d.ts
scripts/update-icons.ts

Added script to generate icons

---

modules/tab/package.json
modules/tab/tsconfig.json

Tab component didn't own a tsconfig which causes publish to fail.

fix(tab/package.json): fix tab component package - missing tsconfig

---

modules/dropdown/Dropdown.tsx
modules/dropdown/MultipleDropdown.tsx
modules/popover/Popover.tsx

improvement(dropdown): refactor Dropdown as we start to implement it in ddm

---

README.md

As per title
No documentation about how to publish packages.

docs(readme.md): update README.md to include publish workflow

---

modules/dropdown/Dropdown.tsx
modules/dropdown/MultipleDropdown.tsx
modules/popover/Popover.story.mdx
modules/popover/Popover.story.tsx
modules/popover/Popover.tsx

fix(dropdown): fix Dropdown custom header to always be a function

---

README.md
modules/card/Card.story.mdx
modules/card/Card.story.tsx
modules/card/Card.tsx
modules/card/CardBody.tsx
modules/card/CardFooter.tsx
modules/card/CardHeader.tsx
modules/card/README.md
modules/card/index.ts
modules/card/package.json
modules/card/tsconfig.json
modules/tokens/themes/theme.default.ts
modules/types/types.ts
modules/typography/Typography.tsx
modules/typography/index.ts

The Card module includes the Card component as well as the CardHeader, CardBody and CardFooter
components

feat(card): add the Card module to diana-ui

---

.eslintrc.js
modules/card/Card.tsx
modules/card/CardBody.tsx
modules/card/CardFooter.tsx
modules/card/CardHeader.tsx
modules/checkbox/Checkbox.tsx
modules/chip/ChipInput.tsx
modules/chip/ChipList.tsx
modules/divider/Divider.tsx
modules/dropdown/Dropdown.tsx
modules/dropdown/MultipleDropdown.tsx
modules/form/Form.tsx
modules/hooks/useOnClickOutside.ts
modules/modal/Modal.tsx
modules/modal/ModalBody.tsx
modules/modal/ModalFooter.tsx
modules/modal/ModalHeader.tsx
modules/notification/Notification.tsx
modules/notification/NotificationStack.tsx
modules/popover/Popover.tsx
modules/portal/Portal.tsx
modules/radio/Radio.tsx
modules/radio/RadioGroup.tsx

- Change useOnClickOutside to accept an array of refs
- Disable Dropdown if items length === 0
- Add possibility to add custom className to all components

Fix Dropdown bugs introduced by Portal.

---

modules/assets/package.json
modules/base/package.json
modules/button/package.json
modules/checkbox/package.json
modules/chip/package.json
modules/divider/package.json
modules/dropdown/package.json
modules/form/package.json
modules/hooks/package.json
modules/icon/package.json
modules/modal/package.json
modules/notification/package.json
modules/popover/package.json
modules/radio/package.json
modules/tab/package.json
modules/textInput/package.json
modules/tokens/package.json
modules/types/package.json
modules/typography/package.json
modules/utils/package.json
package.json
scaffold/package.json.scaffold
yarn.lock

chore(watch): script to watch changes on packages

---

modules/icon/Icon.tsx
modules/textInput/ErrorTextInput.tsx
modules/textInput/TextInput.story.mdx
modules/textInput/TextInput.tsx
modules/textInput/package.json

Added prefix/suffix icon to TextInput;
Added hint to ErrorTextInput

TextInput with prefix/suffix and hint

---

modules/card/CardHeader.tsx
modules/expandable-panel/ExpandablePanel.tsx
modules/expandable-panel/package.json
modules/notification/Notification.tsx
modules/radio/Radio.tsx
modules/tokens/themes/theme.default.ts
modules/types/types.ts
modules/typography/Typography.tsx
modules/typography/index.ts
yarn.lock

As per title
On dmc app some new typography elements needed added. So now the typography is synced with figma design-system

fix(typography): sync typography with design-system figma

---

.gitignore
modules/avatar/Avatar.story.mdx
modules/avatar/Avatar.story.tsx
modules/avatar/Avatar.tsx
modules/avatar/README.md
modules/avatar/index.ts
modules/avatar/package.json
modules/avatar/tsconfig.json
modules/infoicon/Infoicon.story.mdx
modules/infoicon/Infoicon.story.tsx
modules/infoicon/Infoicon.tsx
modules/infoicon/README.md
modules/infoicon/index.ts
modules/infoicon/package.json
modules/infoicon/tsconfig.json

feat(avatar/infoicon): added avatar and iconinfo components

---

modules/avatar/Avatar.story.mdx
modules/avatar/Avatar.story.tsx
modules/avatar/ImageAvatar.tsx
modules/infoicon/Infoicon.story.mdx
modules/infoicon/Infoicon.story.tsx
modules/infoicon/Infoicon.tsx
modules/infoicon/index.ts

feat(infoicon.tsx): info icon component

---

modules/dropdown/BaseMultipleDropdown.tsx
modules/dropdown/Dropdown.tsx
modules/menu/Menu.story.mdx
modules/menu/Menu.tsx
modules/menu/MenuItem.tsx
modules/menu/README.md
modules/menu/index.ts
modules/menu/package.json
modules/menu/tsconfig.json
modules/popover/Popover.tsx
modules/popover/index.ts

menu component

---

modules/card/CardHeader.tsx
modules/infoicon/Infoicon.tsx
yarn.lock

fix(card|infoicon): small fixes on card & infoicon components

---

modules/dropdown/BaseMultipleDropdown.tsx

https://app.zenhub.com/workspaces/frontend-5d53e21db880a7648631a4f7/issues/carlsberggbs/dmbuddy-offshift/502

fix(filtersdropdown.tsx): fix filters dropdown header

---

modules/tab/Tab.story.mdx
modules/tab/Tab.tsx
modules/tab/TabGroup.tsx
modules/tab/package.json
yarn.lock

feat(tab): complete tabs

---

modules/notification/Notification.story.mdx
modules/notification/NotificationContext.ts
modules/notification/NotificationStack.story.tsx
modules/notification/index.ts

Add NotificationContext to allow adding/ removing notifications easily in an application.

improvement(notification): add notification context

---

modules/carousel/Carousel.tsx
modules/carousel/package.json
package.json
yarn.lock

feat(carousel.tsx): added auto-focus after scroll on carousel component

---

modules/sidebar/README.md
modules/sidebar/Sidebar.story.mdx
modules/sidebar/Sidebar.story.tsx
modules/sidebar/Sidebar.tsx
modules/sidebar/index.ts
modules/sidebar/package.json
modules/sidebar/tsconfig.json

The props are all toggled with buttons on the story

Sidebar component 
